pilot_minus1:
  cpus: 8
  memory_gb: 32
  walltime: "01:00:00"
pilot0:
  cpus: 8
  memory_gb: 32
  walltime: "02:00:00"
pilots12:
  gpus: "a100:1"
  cpus: 12
  memory_gb: 64
  walltime: "12:00:00"
  array_concurrency: 3
aggregate:
  cpus: 4
  memory_gb: 16
  walltime: "01:00:00"
